/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Font;
import java.util.Locale;

/**
 *
 * @author saipr
 */
public class CMai2 extends javax.swing.JFrame
{

    //Variables
    //Variables paneles
    CProgressBar vPnlProgress = new CProgressBar();
    CPnlSupFuente vPnSupInterior = new CPnlSupFuente();
    CPnlSupTamaño vPnlSupInterfaz = new CPnlSupTamaño();
    public static CPnlContenido1 vPnlContenido1 = new CPnlContenido1();
    public static CPnlContenido2 vPnlContenido2 = new CPnlContenido2();

    public CMai2()
    {

        initComponents();
        initMyComponents();
    }

    public void initMyComponents()
    {
        //contenidos();
        barraDeCarga();
        barraDeHerramientasSuperior();
        desactivarBotones();

    }

    public void desactivarBotones()
    {
        if (vPnlContenido1.isVisible())
        {
            vBtnAnterior.setEnabled(false);
            vBtnSiguiente.setEnabled(true);
        } else if (vPnlContenido2.isVisible())
        {
            vBtnAnterior.setEnabled(true);
            vBtnSiguiente.setEnabled(false);
        }
    }

    public void barraDeHerramientasSuperior()
    {
        vTbpnlSup.setFont(new Font("Segoe UI Black", 1, 18));
        vTbpnlSup.addTab("Interno", vPnSupInterior);
        vTbpnlSup.addTab("Interfaz", vPnlSupInterfaz);
    }

    public void barraDeCarga()
    {
        vPnlInf.setVisible(false);
        vTbpnlSup.setVisible(false);
        vPnlProgress.setVisible(true);
        vPnlPrinCent.add(vPnlProgress);
        vPnlProgress.initBarraProgreso();
    }

    public void contenidos()
    {
        vPnlContenido1.setVisible(false);
        vPnlContenido2.setVisible(false);
        vPnlPrinCent.add(vPnlContenido1);
        vPnlPrinCent.add(vPnlContenido2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        vPnlPrin = new javax.swing.JPanel();
        vPnlInf = new javax.swing.JPanel();
        vBtnAnterior = new javax.swing.JButton();
        vBtnSiguiente = new javax.swing.JButton();
        vPnlPrinCent = new javax.swing.JPanel();
        vTbpnlSup = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 1");
        setMinimumSize(new java.awt.Dimension(720, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        vPnlPrin.setBackground(new java.awt.Color(204, 255, 255));
        vPnlPrin.setLayout(new java.awt.BorderLayout());

        vPnlInf.setBackground(new java.awt.Color(61, 64, 91));

        vBtnAnterior.setBackground(new java.awt.Color(242, 204, 143));
        vBtnAnterior.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        vBtnAnterior.setForeground(new java.awt.Color(61, 64, 91));
        vBtnAnterior.setText("Anterior");
        vBtnAnterior.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vBtnAnteriorActionPerformed(evt);
            }
        });
        vPnlInf.add(vBtnAnterior);

        vBtnSiguiente.setBackground(new java.awt.Color(242, 204, 143));
        vBtnSiguiente.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        vBtnSiguiente.setForeground(new java.awt.Color(61, 64, 91));
        vBtnSiguiente.setText("Siguiente");
        vBtnSiguiente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vBtnSiguienteActionPerformed(evt);
            }
        });
        vPnlInf.add(vBtnSiguiente);

        vPnlPrin.add(vPnlInf, java.awt.BorderLayout.PAGE_END);

        vPnlPrinCent.setBackground(new java.awt.Color(255, 255, 255));
        vPnlPrinCent.setLayout(new java.awt.BorderLayout());
        vPnlPrin.add(vPnlPrinCent, java.awt.BorderLayout.CENTER);

        vTbpnlSup.setBackground(new java.awt.Color(242, 204, 143));
        vTbpnlSup.setForeground(new java.awt.Color(61, 64, 91));
        vTbpnlSup.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vTbpnlSupStateChanged(evt);
            }
        });
        vPnlPrin.add(vTbpnlSup, java.awt.BorderLayout.NORTH);

        getContentPane().add(vPnlPrin);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Guardar esta configuracion (Demostrativo)");
        jMenu1.add(jMenuItem1);

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Cargar antigua configuracion (Demostrativo)");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Otros");

        jMenuItem3.setText("Acerca de...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vBtnSiguienteActionPerformed
    {//GEN-HEADEREND:event_vBtnSiguienteActionPerformed
        vPnlContenido1.setVisible(false);
        vPnlContenido2.setVisible(true);
        vPnlPrinCent.add(vPnlContenido2);
        desactivarBotones();
        vTbpnlSup.setVisible(false);
        vPnlPrinCent.validate();
    }//GEN-LAST:event_vBtnSiguienteActionPerformed

    private void vBtnAnteriorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vBtnAnteriorActionPerformed
    {//GEN-HEADEREND:event_vBtnAnteriorActionPerformed
        vPnlContenido2.setVisible(false);
        vPnlContenido1.setVisible(true);
        vPnlPrinCent.add(vPnlContenido1);
        desactivarBotones();
        vTbpnlSup.setVisible(true);
        vPnlPrinCent.validate();
    }//GEN-LAST:event_vBtnAnteriorActionPerformed

    private void vTbpnlSupStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vTbpnlSupStateChanged
    {//GEN-HEADEREND:event_vTbpnlSupStateChanged
        if (vTbpnlSup.getSelectedIndex() == 0)
        {
            CPnlContenido1.restaurarComponentesSeleccionados();
        } else if (vTbpnlSup.getSelectedIndex() == 1)
        {
            CPnlContenido1.seleccionarComponente(0);
        }
    }//GEN-LAST:event_vTbpnlSupStateChanged

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem3ActionPerformed
        CPnlAcercaDe obj = new CPnlAcercaDe(this, true);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton vBtnAnterior;
    private javax.swing.JButton vBtnSiguiente;
    public static javax.swing.JPanel vPnlInf;
    private javax.swing.JPanel vPnlPrin;
    public static javax.swing.JPanel vPnlPrinCent;
    public static javax.swing.JTabbedPane vTbpnlSup;
    // End of variables declaration//GEN-END:variables
}
