/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author saipr
 */
public class CPnlContenido2 extends javax.swing.JPanel
{

    /**
     * Creates new form CPnlContenido2
     */
    public CPnlContenido2()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vTableComponentesUsados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setText("Componentes usados");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        vTableComponentesUsados.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        vTableComponentesUsados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {1, "jList"},
                {2, "jLabel"},
                {3, "jButton"},
                {4, "jComboBox"},
                {5, "jTextAre"},
                {6, "jTextField"},
                {7, "jPanel"},
                {8, "jToggleButton"},
                {9, "jSlider"},
                {10, "jRadioButton"},
                {11, "jSpinner"},
                {12, "jButtonGroup"},
                {13, "jProgressBar"},
                {14, "jFrame"},
                {15, "jDialog"},
                {16, "jMenuBar"},
                {17, "jColorChooser"},
                {18, "jTable"},
                {19, "jCheckBox"},
                {20, "jFormattedField"},
                {21, "jPasswordField"},
                {22, "jScrollPane"},
                {23, "jSeparator"},
                {24, "jTabbed Pane"},
                {25, "jScrollBar"},
                {26, "jMenuItem"}
            },
            new String []
            {
                "Numero", "Componente"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        vTableComponentesUsados.setToolTipText("Componentes usados");
        jScrollPane1.setViewportView(vTableComponentesUsados);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setText("Creado por: Sandro de Jesus Hernandez Del Angel");
        jPanel2.add(jLabel2);

        jLabel3.setText("Este programa es unicamente para la demostracion del uso de los componentes SWING");
        jPanel2.add(jLabel3);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable vTableComponentesUsados;
    // End of variables declaration//GEN-END:variables
}
