/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.util.Calendar;
import javax.swing.border.LineBorder;

/**
 *
 * @author saipr
 */
public class CPnlContenido1 extends javax.swing.JPanel
{

    String hora, minutos, segundos, ampm;
    Calendar calendario;
    Thread h;
    public static boolean bLbl1 = true, bLbl2 = false, bLbl3 = false, bLbl4 = false, bPnl3 = false, bPnl4 = false;
    Reloj reloj = new Reloj();
    public static LineBorder bordeAlSeleccionar = new LineBorder(Color.red, 4);

    /**
     * Creates new form CPnlCentro
     */
    public CPnlContenido1()
    {
        initComponents();
        vTgbtnHora.setSelected(true);

    }

    public void initMyComponents()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        vBtngroupFechaHora = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        vBtnCambtxt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        vTgbtnFecha = new javax.swing.JToggleButton();
        vTgbtnHora = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        v2EditLbl1.setBackground(new java.awt.Color(204, 255, 255));
        v2EditLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        v2EditLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v2EditLbl1.setText("Este es un jLabel");
        v2EditLbl1.setOpaque(true);
        v2EditLbl1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                v2EditLbl1MousePressed(evt);
            }
        });
        jPanel3.add(v2EditLbl1, java.awt.BorderLayout.PAGE_START);

        vEditLblLabelEditable.setBackground(new java.awt.Color(255, 255, 255));
        vEditLblLabelEditable.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        vEditLblLabelEditable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vEditLblLabelEditable.setText("jLabel3");
        vEditLblLabelEditable.setOpaque(true);
        jPanel3.add(vEditLblLabelEditable, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        v2EditLbl2.setBackground(new java.awt.Color(204, 204, 255));
        v2EditLbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        v2EditLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v2EditLbl2.setText("Aqui hay un jTextArea para editar");
        v2EditLbl2.setOpaque(true);
        v2EditLbl2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                v2EditLbl2MousePressed(evt);
            }
        });
        jPanel2.add(v2EditLbl2, java.awt.BorderLayout.PAGE_START);

        vEditTextAreaEditamePlz.setColumns(20);
        vEditTextAreaEditamePlz.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        vEditTextAreaEditamePlz.setRows(5);
        vEditTextAreaEditamePlz.setText("Editame plzz!!!");
        jScrollPane1.setViewportView(vEditTextAreaEditamePlz);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setLayout(new java.awt.BorderLayout());

        v2EditLbl3.setBackground(new java.awt.Color(255, 255, 204));
        v2EditLbl3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        v2EditLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v2EditLbl3.setText("Cambiar el texto del jLabel");
        v2EditLbl3.setOpaque(true);
        v2EditLbl3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                v2EditLbl3MousePressed(evt);
            }
        });
        jPanel5.add(v2EditLbl3, java.awt.BorderLayout.PAGE_END);

        v2EditPnl3.setBackground(new java.awt.Color(255, 255, 204));
        v2EditPnl3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                v2EditPnl3MousePressed(evt);
            }
        });
        v2EditPnl3.setLayout(new java.awt.GridBagLayout());

        vEditLblTextaqui.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        vEditLblTextaqui.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vEditLblTextaqui.setText("Ingrese texto aquí");
        vEditLblTextaqui.setToolTipText("El texto que pongas aqui se sobrecribira arriba al presionar el boton");
        vEditLblTextaqui.setPreferredSize(new java.awt.Dimension(1, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.ipady = 18;
        v2EditPnl3.add(vEditLblTextaqui, gridBagConstraints);

        vBtnCambtxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tick1_32px.png"))); // NOI18N
        vBtnCambtxt.setToolTipText("Presioname para la magia");
        vBtnCambtxt.setAlignmentY(0.0F);
        vBtnCambtxt.setBorder(null);
        vBtnCambtxt.setBorderPainted(false);
        vBtnCambtxt.setContentAreaFilled(false);
        vBtnCambtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtnCambtxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vBtnCambtxt.setMargin(new java.awt.Insets(0, 0, 0, 0));
        vBtnCambtxt.setPreferredSize(new java.awt.Dimension(32, 32));
        vBtnCambtxt.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tick2_32px.png"))); // NOI18N
        vBtnCambtxt.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vBtnCambtxtActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        v2EditPnl3.add(vBtnCambtxt, gridBagConstraints);

        jPanel5.add(v2EditPnl3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setLayout(new java.awt.BorderLayout());

        v2EditLbl4.setBackground(new java.awt.Color(204, 255, 204));
        v2EditLbl4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        v2EditLbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v2EditLbl4.setText("Mas elementos swing");
        v2EditLbl4.setOpaque(true);
        v2EditLbl4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                v2EditLbl4MousePressed(evt);
            }
        });
        jPanel4.add(v2EditLbl4, java.awt.BorderLayout.PAGE_END);

        v2EditPnl4.setBackground(new java.awt.Color(204, 255, 204));
        v2EditPnl4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                v2EditPnl4MousePressed(evt);
            }
        });
        v2EditPnl4.setLayout(new java.awt.GridBagLayout());

        vTgbtnFecha.setBackground(new java.awt.Color(204, 255, 204));
        vBtngroupFechaHora.add(vTgbtnFecha);
        vTgbtnFecha.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        vTgbtnFecha.setText("Fecha");
        vTgbtnFecha.setBorderPainted(false);
        vTgbtnFecha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtnFechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        v2EditPnl4.add(vTgbtnFecha, gridBagConstraints);

        vTgbtnHora.setBackground(new java.awt.Color(204, 255, 204));
        vBtngroupFechaHora.add(vTgbtnHora);
        vTgbtnHora.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        vTgbtnHora.setSelected(true);
        vTgbtnHora.setText("Horas");
        vTgbtnHora.setBorderPainted(false);
        vTgbtnHora.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtnHoraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        v2EditPnl4.add(vTgbtnHora, gridBagConstraints);

        vEditLblFechaHora.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        vEditLblFechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vEditLblFechaHora.setText("24:12:00");
        vEditLblFechaHora.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(13, 0, 13, 0);
        v2EditPnl4.add(vEditLblFechaHora, gridBagConstraints);

        jPanel4.add(v2EditPnl4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void vBtnCambtxtActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vBtnCambtxtActionPerformed
    {//GEN-HEADEREND:event_vBtnCambtxtActionPerformed
        vEditLblLabelEditable.setText(vEditLblTextaqui.getText());
    }//GEN-LAST:event_vBtnCambtxtActionPerformed

    private void vTgbtnFechaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtnFechaActionPerformed
    {//GEN-HEADEREND:event_vTgbtnFechaActionPerformed
        reloj.setB(false);
    }//GEN-LAST:event_vTgbtnFechaActionPerformed

    private void vTgbtnHoraActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtnHoraActionPerformed
    {//GEN-HEADEREND:event_vTgbtnHoraActionPerformed
        reloj = new Reloj();
        vEditLblFechaHora.setText("hola");
    }//GEN-LAST:event_vTgbtnHoraActionPerformed

    private void v2EditLbl1MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_v2EditLbl1MousePressed
    {//GEN-HEADEREND:event_v2EditLbl1MousePressed
        seleccionarComponente(0);
    }//GEN-LAST:event_v2EditLbl1MousePressed

    private void v2EditLbl2MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_v2EditLbl2MousePressed
    {//GEN-HEADEREND:event_v2EditLbl2MousePressed
        seleccionarComponente(1);
    }//GEN-LAST:event_v2EditLbl2MousePressed

    private void v2EditLbl3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_v2EditLbl3MousePressed
    {//GEN-HEADEREND:event_v2EditLbl3MousePressed
        seleccionarComponente(2);
    }//GEN-LAST:event_v2EditLbl3MousePressed

    private void v2EditLbl4MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_v2EditLbl4MousePressed
    {//GEN-HEADEREND:event_v2EditLbl4MousePressed
        seleccionarComponente(3);
    }//GEN-LAST:event_v2EditLbl4MousePressed

    private void v2EditPnl3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_v2EditPnl3MousePressed
    {//GEN-HEADEREND:event_v2EditPnl3MousePressed
        seleccionarComponente(4);
    }//GEN-LAST:event_v2EditPnl3MousePressed

    private void v2EditPnl4MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_v2EditPnl4MousePressed
    {//GEN-HEADEREND:event_v2EditPnl4MousePressed
        seleccionarComponente(5);
    }//GEN-LAST:event_v2EditPnl4MousePressed

    /**
     * Este metodo selecciona el componente seleccionado solo si estas en las
     * pestaña 2 del jTbPane de la barra de herramientas\ sirve para cuando
     * haces click en el componente en esta clase o cuando seleccionas un
     * componente desde el jList dela barra de herramientas
     *
     * @param opc Numero del componente donde: opc = 0 -> Selecciona al
     * v2EditLbl1 opc = 1 -> Selecciona al v2EditLbl2 opc = 2 -> Selecciona al
     * v2EditLbl3 opc = 3 -> Selecciona al v2EditLbl4 opc = 4 -> Selecciona al
     * v2EditPnl3 opc = 5 -> Selecciona al v2EditPnl4
     */
    public static void seleccionarComponente(int opc)
    {
        try
        {
            if (CMai2.vTbpnlSup.getSelectedIndex() == 1)
            {
                restaurarComponentesSeleccionados();
                switch (opc)
                {
                    case 0:
                        CPnlSupTamaño.vListapaneles.setSelectedIndex(0);
                        bLbl1 = true;
                        v2EditLbl1.setBorder(bordeAlSeleccionar);
                        break;
                    case 1:
                        CPnlSupTamaño.vListapaneles.setSelectedIndex(1);
                        bLbl2 = true;
                        v2EditLbl2.setBorder(bordeAlSeleccionar);
                        break;
                    case 2:
                        CPnlSupTamaño.vListapaneles.setSelectedIndex(2);
                        bLbl3 = true;
                        v2EditLbl3.setBorder(bordeAlSeleccionar);
                        break;
                    case 3:
                        CPnlSupTamaño.vListapaneles.setSelectedIndex(3);
                        bLbl4 = true;
                        v2EditLbl4.setBorder(bordeAlSeleccionar);
                        break;
                    case 4:
                        CPnlSupTamaño.vListapaneles.setSelectedIndex(4);
                        bPnl3 = true;
                        v2EditPnl3.setBorder(bordeAlSeleccionar);
                        break;
                    case 5:
                        CPnlSupTamaño.vListapaneles.setSelectedIndex(5);
                        bPnl4 = true;
                        v2EditPnl4.setBorder(bordeAlSeleccionar);
                        break;
                }
            }
        } catch (Exception e)
        {
        }
    }

    /**
     * Este metodo vuelve todos los componentes seleccionados a su deafult, solo
     * sirve para la opcion de interfaz del jTabbedPane, es para que sea mas
     * facil cambiar los bordes de cada componente
     */
    public static void restaurarComponentesSeleccionados()
    {
        v2EditLbl1.setBorder(null);
        v2EditLbl2.setBorder(null);
        v2EditLbl3.setBorder(null);
        v2EditLbl4.setBorder(null);
        v2EditPnl3.setBorder(null);
        v2EditPnl4.setBorder(null);
        bLbl1 = false;
        bLbl2 = false;
        bLbl3 = false;
        bLbl4 = false;
        bPnl3 = false;
        bPnl4 = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JLabel v2EditLbl1 = new javax.swing.JLabel();
    public static final javax.swing.JLabel v2EditLbl2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel v2EditLbl3 = new javax.swing.JLabel();
    public static final javax.swing.JLabel v2EditLbl4 = new javax.swing.JLabel();
    public static final javax.swing.JPanel v2EditPnl3 = new javax.swing.JPanel();
    public static final javax.swing.JPanel v2EditPnl4 = new javax.swing.JPanel();
    private javax.swing.JButton vBtnCambtxt;
    private javax.swing.ButtonGroup vBtngroupFechaHora;
    public static final javax.swing.JLabel vEditLblFechaHora = new javax.swing.JLabel();
    public static final javax.swing.JLabel vEditLblLabelEditable = new javax.swing.JLabel();
    public static final javax.swing.JTextField vEditLblTextaqui = new javax.swing.JTextField();
    public static final javax.swing.JTextArea vEditTextAreaEditamePlz = new javax.swing.JTextArea();
    private javax.swing.JToggleButton vTgbtnFecha;
    private javax.swing.JToggleButton vTgbtnHora;
    // End of variables declaration//GEN-END:variables
}
