/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author saipr
 */
public class CProgressBar extends javax.swing.JPanel
{
    
    int start = 0;
    Timer timer = null;
    
    public CProgressBar()
    {
        initComponents();
    }
    
    public void initBarraProgreso()
    {
        
        timer = new Timer(1, new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                start++;
                if (start == 100)
                {
                    timer.stop();
                    vProgressBar.setVisible(false);
                    setVisible(false);
                    CMai2.vTbpnlSup.setVisible(true);
                    CMai2.vPnlInf.setVisible(true);
                    CMai2.vTbpnlSup.setVisible(true);
                    CMai2.vPnlContenido1.setVisible(true);
                    CMai2.vPnlContenido2.setVisible(false);
                    CMai2.vPnlPrinCent.add(CMai2.vPnlContenido1);
                    
                    CMai2.vPnlPrinCent.validate();
                }
                vProgressBar.setValue(start);
                vLblPorcentaje.setText(start + "%");
            }
        });
        timer.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        vProgressBar = new javax.swing.JProgressBar();
        vLblPorcentaje = new javax.swing.JLabel();
        vLblEspere1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1080, 720));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(46, 196, 182));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        vProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        vProgressBar.setForeground(new java.awt.Color(231, 29, 54));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(vProgressBar, gridBagConstraints);

        vLblPorcentaje.setBackground(new java.awt.Color(255, 159, 28));
        vLblPorcentaje.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        vLblPorcentaje.setForeground(new java.awt.Color(253, 255, 252));
        vLblPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblPorcentaje.setText("Espere porfavor");
        vLblPorcentaje.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel1.add(vLblPorcentaje, gridBagConstraints);

        vLblEspere1.setBackground(new java.awt.Color(255, 159, 28));
        vLblEspere1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        vLblEspere1.setForeground(new java.awt.Color(253, 255, 252));
        vLblEspere1.setText("Espere porfavor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(vLblEspere1, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel vLblEspere1;
    private javax.swing.JLabel vLblPorcentaje;
    private javax.swing.JProgressBar vProgressBar;
    // End of variables declaration//GEN-END:variables
}
